# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timestamp_dialog_alt.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_manualTimestampDialog(object):
    def setupUi(self, manualTimestampDialog):
        manualTimestampDialog.setObjectName("manualTimestampDialog")
        manualTimestampDialog.resize(1090, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(manualTimestampDialog.sizePolicy().hasHeightForWidth())
        manualTimestampDialog.setSizePolicy(sizePolicy)
        manualTimestampDialog.setSizeGripEnabled(True)
        self.formLayout = QtWidgets.QFormLayout(manualTimestampDialog)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(manualTimestampDialog)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(manualTimestampDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frameNum1 = QtWidgets.QLineEdit(manualTimestampDialog)
        self.frameNum1.setObjectName("frameNum1")
        self.verticalLayout.addWidget(self.frameNum1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(manualTimestampDialog)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.hh1 = QtWidgets.QLineEdit(manualTimestampDialog)
        self.hh1.setObjectName("hh1")
        self.verticalLayout_2.addWidget(self.hh1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(manualTimestampDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.mm1 = QtWidgets.QLineEdit(manualTimestampDialog)
        self.mm1.setObjectName("mm1")
        self.verticalLayout_3.addWidget(self.mm1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(manualTimestampDialog)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.ss1 = QtWidgets.QLineEdit(manualTimestampDialog)
        self.ss1.setObjectName("ss1")
        self.verticalLayout_4.addWidget(self.ss1)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(manualTimestampDialog)
        self.label_10.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(manualTimestampDialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.frameNum2 = QtWidgets.QLineEdit(manualTimestampDialog)
        self.frameNum2.setObjectName("frameNum2")
        self.verticalLayout_5.addWidget(self.frameNum2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(manualTimestampDialog)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.hh2 = QtWidgets.QLineEdit(manualTimestampDialog)
        self.hh2.setObjectName("hh2")
        self.verticalLayout_6.addWidget(self.hh2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(manualTimestampDialog)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.mm2 = QtWidgets.QLineEdit(manualTimestampDialog)
        self.mm2.setObjectName("mm2")
        self.verticalLayout_7.addWidget(self.mm2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(manualTimestampDialog)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.ss2 = QtWidgets.QLineEdit(manualTimestampDialog)
        self.ss2.setObjectName("ss2")
        self.verticalLayout_8.addWidget(self.ss2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(manualTimestampDialog)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_12 = QtWidgets.QLabel(manualTimestampDialog)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.frameDeltaTime = QtWidgets.QLineEdit(manualTimestampDialog)
        self.frameDeltaTime.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.frameDeltaTime.setObjectName("frameDeltaTime")
        self.verticalLayout_9.addWidget(self.frameDeltaTime)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_5)
        self.buttonBox = QtWidgets.QDialogButtonBox(manualTimestampDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.buttonBox)

        self.retranslateUi(manualTimestampDialog)
        self.buttonBox.accepted.connect(manualTimestampDialog.accept)
        self.buttonBox.rejected.connect(manualTimestampDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(manualTimestampDialog)
        manualTimestampDialog.setTabOrder(self.frameNum1, self.hh1)
        manualTimestampDialog.setTabOrder(self.hh1, self.mm1)
        manualTimestampDialog.setTabOrder(self.mm1, self.ss1)
        manualTimestampDialog.setTabOrder(self.ss1, self.frameNum2)
        manualTimestampDialog.setTabOrder(self.frameNum2, self.hh2)
        manualTimestampDialog.setTabOrder(self.hh2, self.mm2)
        manualTimestampDialog.setTabOrder(self.mm2, self.ss2)
        manualTimestampDialog.setTabOrder(self.ss2, self.frameDeltaTime)

    def retranslateUi(self, manualTimestampDialog):
        _translate = QtCore.QCoreApplication.translate
        manualTimestampDialog.setWindowTitle(_translate("manualTimestampDialog", "Manual Timestamp Entry"))
        self.label_9.setText(_translate("manualTimestampDialog", "<html><head/><body><p>Timestamp for early frame ...</p></body></html>"))
        self.label.setText(_translate("manualTimestampDialog", "frame num"))
        self.label_2.setText(_translate("manualTimestampDialog", "hh"))
        self.label_3.setText(_translate("manualTimestampDialog", "mm"))
        self.label_4.setText(_translate("manualTimestampDialog", "ss.ssss"))
        self.label_10.setText(_translate("manualTimestampDialog", "<html><head/><body><p>Timestamp for later frame ...</p></body></html>"))
        self.label_5.setText(_translate("manualTimestampDialog", "frame num"))
        self.label_6.setText(_translate("manualTimestampDialog", "hh"))
        self.label_7.setText(_translate("manualTimestampDialog", "mm"))
        self.label_8.setText(_translate("manualTimestampDialog", "ss.ssss"))
        self.label_11.setText(_translate("manualTimestampDialog", "<html><head/><body><p>or delta time between frames ...</p></body></html>"))
        self.label_12.setText(_translate("manualTimestampDialog", "time between frames"))

